### ISSUE TITLE
Force the latest guava library when running gauge from command line

### ISSUE THREAD

**Issue by sofas** [getgauge/gauge-java#131]
### Expected behavior
Run gauge from command line should take guava-{version}.jar from the directory configured in `gauge_additional_libs` property

### Actual behavior
Guava from gauge-java plugin installation libs directory is used instead. 

### Steps to reproduce
1. In pom.xml force guava version to the 23.6-jre used in the latest 4.10.01 version of selenide 
2. Run `mvn clean install`  
3. guava-23.6-jre.jar is added in the target libs directory: `target/my-project/WEB-INF/lib`
4. Add path to this directory in `gauge_additional_libs` property: `gauge_additional_libs = libs/* ,target/my-project/WEB-INF/lib/*`
5. Run `gauge run specs` from command line
6. Command fails with error message:

```
java.lang.NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
        at org.openqa.selenium.net.UrlChecker.<init>(UrlChecker.java:62)
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
```

I've tried to change the order of additional libs without success:
 ```
gauge_additional_libs = target/my-project/WEB-INF/lib/*, libs/*
 ```
I've also tried to replace guava-21.0.jar by guava-23.6-jre.jar in the gauge-java plugin installation folder and it works, but it's certainly not the best option. 

Test works fine from Intellij.

### Gauge version
```
> gauge -v
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
spectacle (0.1.2)
```

**Comment by flickerlight** [comment]
"replace guava-21.0.jar by guava-23.6-jre.jar" I had to do this just then. Otherwise I could use latest selenium library for it depends on guava-23.6.

**Comment by jorgecunhamorsum** [comment]
I had this exact same problem and I had to manually replace the jar file otherwise I wouldn't be able to run my code.

**Comment by sriv** [comment]
Thanks for bringing this up.

I guess this could be extended to all the dependencies and not just `guava`.

**Comment by Thunderforge** [comment]
@sriv Would this be fixable by just adding `force=true` to all of the dependencies in `pom.xml` (or at least the important ones)?

**Comment by nehashri** [comment]
@Thunderforge we have updated the guava version with the latest gauge-java. It should be available in nightly version of the plugin. We are going to make a release of the plugin soon, so it should be available with the stable version too.
