### ISSUE TITLE
Run gauge tests with sahi in parallel with multithreading

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge-java#135]
Hi!

As I already wrote in this issue (https://github.com/getgauge/gauge-java/issues/61) I am always getting an exception when running the gauge tests with multithreading = true  in parallel mode.

I have tried with your gauge-example-sahi project (see https://github.com/getgauge-examples/gauge-example-sahi) as well as with my own project and I always get the same exception sooner or later while the tests run in parallel. (see exception in actual behavior)

I am working with the sahi support team on the problem for a long time, but they cannot come to any solution and as you are offering an example how to use gauge with sahi I would really appreciate it, if you could try to find a solution for this problem.

I have been testing with your example project, so it should not be that difficult for you to reproduce. (I can also send you the project)

### Expected behavior
no exception when running tests in parallel

### Actual behavior

Exception in the log

INFORMATION: Kill: [20288, 20732, 20040, 12804, 19472, 9248, 6560, 19944, 18112, 18296, 16764, 20088, 20420]tearDown suite
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at net.sf.sahi.util.Utils.readURLThrowException(Utils.java:244)
	at net.sf.sahi.util.Utils.readURLThrowException(Utils.java:214)
	at net.sf.sahi.util.Utils.readURL(Utils.java:205)
	at net.sf.sahi.util.Utils.readURL(Utils.java:165)
	at com.sahipro.lang.java.client.BrowserBase.execCommand(Unknown Source)
	at com.sahipro.lang.java.client.BrowserBase.executeStep2(Unknown Source)
	at com.sahipro.lang.java.client.BrowserBase.executeStep(Unknown Source)
	at com.sahipro.lang.java.client.BrowserBase.executeStep(Unknown Source)
	at com.sahipro.lang.java.client.BrowserBase.executeSahi(Unknown Source)
	at com.sahipro.lang.java.client.BrowserAutoGen.navigateTo(Unknown Source)
	at com.thoughtworks.gauge.example.pages.CustomerPage.navigate(CustomerPage.java:16)
	at com.thoughtworks.gauge.example.Customer.navigateToCustomersPage(Customer.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:38)
	at com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:74)
	at com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:67)
	at com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:49)
	at com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
	at com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
	at com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:41)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
	at com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
	at com.thoughtworks.gauge.GaugeRuntime$1.run(GaugeRuntime.java:74)
	at java.lang.Thread.run(Thread.java:745)
Failed: On the customer page
Filename: C:\projects\gauge-example-sahi-master\specs\user1.spec:18
Message: java.lang.NullPointerException
Stack Trace:
java.lang.String.<init>(String.java:491)
com.sahipro.lang.java.client.BrowserBase.execCommand(Unknown Source)
com.sahipro.lang.java.client.BrowserBase.executeStep2(Unknown Source)
com.sahipro.lang.java.client.BrowserBase.executeStep(Unknown Source)
com.sahipro.lang.java.client.BrowserBase.executeStep(Unknown Source)
com.sahipro.lang.java.client.BrowserBase.executeSahi(Unknown Source)
com.sahipro.lang.java.client.BrowserAutoGen.navigateTo(Unknown Source)
com.thoughtworks.gauge.example.pages.CustomerPage.navigate(CustomerPage.java:16)
com.thoughtworks.gauge.example.Customer.navigateToCustomersPage(Customer.java:17)

### Steps to reproduce
1. set multithreading to true default.properties

2. run tests in parallel like this 
C:\dev\Gauge\bin\gauge.exe run --machine-readable --hide-suggestion --simple-console --parallel -n 5 C:/projects/gauge-example-sahi-master/specs
in this example I had 6 specs to execute
3. the BrowserFactory.java file has to be adapted, because you do not have to start the sahi proxy several times (see BrowserFactory.java)

### Gauge version
```
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
spectacle (0.1.2)
```

sahi Version 
Sahi Pro v7.5.0 (2017-12-22)

**Comment by kupna** [comment]
BrowserFactory.java

package com.thoughtworks.gauge.example;

import com.sahipro.lang.java.client.Browser;
import com.thoughtworks.gauge.AfterSpec;
import com.thoughtworks.gauge.AfterSuite;
import com.thoughtworks.gauge.BeforeSpec;
import com.thoughtworks.gauge.BeforeSuite;
import net.sf.sahi.Proxy;
import net.sf.sahi.config.Configuration;
import net.sf.sahi.util.Utils;

import java.io.File;
import java.io.IOException;

public class BrowserFactory {
	
	private static final int DEFAULT_PORT = 9999;
	private static Proxy proxy;
	private static ThreadLocal<Browser> browser = ThreadLocal.withInitial(() -> null);

	static {
		initSahi();
		startProxy(DEFAULT_PORT);
	}

	@BeforeSuite
	public void setupSuite() throws IOException {
		System.out.println("setup suite");
		launchBrowser();
	}

	@AfterSuite
	public void tearDownSuite() {
		System.out.println("tearDown suite");
		shutDownBrowser();
	}

	@BeforeSpec
	public void setup() throws IOException {
		System.out.println("setup spec");
		launchBrowser();
	}

	@AfterSpec
	public void tearDown() {
		System.out.println("tearDown spec");
		shutDownBrowser();
	}

	private static void initSahi() {
		System.out.println("init sahi");
		String sahiInstallDir = System.getenv("sahi.install_dir");
		if (sahiInstallDir == null || sahiInstallDir.isEmpty()) {
			throw new RuntimeException("Sahi Install directory not specified. Set in env/default/sahi_config.properties file");
		}
		Configuration.initJava(sahiInstallDir, userDataDir());
	}

	private static void launchBrowser() throws IOException {
		if (getBrowser() == null) {
			String browserName = System.getenv("sahi.browser_name");
			System.out.println(String.format("Launch browser %s", browserName));
			browser.set(new Browser(browserName));
			getBrowser().open();
		}
	}

	private static void shutDownBrowser() {
		if (getBrowser() != null) {
			getBrowser().kill();
//			browser.set(null);
			browser.remove();
		}
	}

	private static void startProxy(int port) {
		System.out.println("start sahi proxy");
		proxy = new Proxy(port);
		proxy.start(true, true);
		waitForProxy();
	}

	public static Browser getBrowser() {
		return browser.get();
	}

	private static String userDataDir() {
		String path = new File("sahi", "userdata").getAbsolutePath();
		System.out.println(String.format("looking for sahi user data under path: %s", path));
		return path;
	}

	private static void waitForProxy() {
		System.out.println("start wait for proxy");
		long startTime = System.currentTimeMillis();

		for (int i = 0; i < 10000; i++) {
			try {
				System.out.println("try waiting for sahi proxy");
				Utils.readURLThrowException("http://localhost:" + DEFAULT_PORT + "/_s_/spr/blank.htm");
				break;
			} catch (Exception e) {
				System.out.println("sahi proxy is not yet started");
			}
			Utils.sleep(10);
		}
		Utils.sleep(3000);
		long endTime = System.currentTimeMillis() - startTime;
		System.out.println(String.format("finished wait for proxy in %s ms", endTime));
	}
}

**Comment by kupna** [comment]
I have just copied the customer.spec, products.spec and user.spec to have 6 specs to run as you can see here. 

![image](https://user-images.githubusercontent.com/12813719/37660538-f552bc2e-2c52-11e8-844e-28ad66ee963a.png)

**Comment by kupna** [comment]
any input on that?

**Comment by BugDiver** [comment]
@kupna  I'm not able to reproduce your issue on the example projects. All specs are passing without any error and all the browsers are closed after finishing the run. I copied all three specs twice.
![screen shot 2018-03-26 at 2 49 52 pm](https://user-images.githubusercontent.com/15309877/37897927-1c582302-3105-11e8-821b-ebead6b4c543.png)

**Comment by kupna** [comment]
@BugDiver 
hi! could you please try again with adding these methods to BrowserFactory.java

	@BeforeSpec
	public void setup() throws IOException {
		logger.info("setup spec");
		launchBrowser();
	}

	@AfterSpec
	public void tearDown() {
		logger.info("tearDown spec");
		shutDownBrowser();
	}

now you should get the exception as well. 

Tell me if it works...

Thx Natalie

**Comment by kupna** [comment]
@BugDiver would you please try again?

**Comment by Apoorva-GA** [comment]
@kupna Does [gauge-example-sahi](https://github.com/getgauge-examples/gauge-example-sahi) work for you without changing the BrowserFactory.java?

I mean, just clone and fallow the instructions in the readme file.[](url)

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
