### ISSUE TITLE
Should not get an error while running tests in parallel

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#139]
**Actual behavior**
On CI, Getting a null-pointer exception while running gauge-tests.
```
java.lang.NullPointerException
        	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:38)
        	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
        	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
        	at com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
        	at com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
        	at java.lang.Thread.run(Thread.java:748)
        java.lang.NullPointerException
```
**Observed on**
* CI - Linux Job of [Java-FT](https://build.getgauge.io/go/tab/build/detail/Java-FT/1299/specs/1/linux)

**Comment by sguptatw** [comment]
Fixed with
```
Gauge version: 0.9.8.nightly-2018-04-11
Commit Hash: 4d314ef

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
java (0.6.7.nightly-2018-04-06)
```
