### ISSUE TITLE
Should be able to implement a parser in the default package

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#142]
_From @sguptatw on April 13, 2018 2:53_

**Expected behavior**
The package of the parser with custom implementation should not be restricted to ``

**Actual behavior**
Getting the following exception
```
/usr/local/bin/gauge run --machine-readable --hide-suggestion --simple-console .../basic4/specs/example.spec:13
java.lang.NullPointerException
	at com.thoughtworks.gauge.execution.parameters.parsers.base.ParameterParsingChain.isNotGaugeParser(ParameterParsingChain.java:32)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.thoughtworks.gauge.execution.parameters.parsers.base.ParameterParsingChain.<init>(ParameterParsingChain.java:25)
	at com.thoughtworks.gauge.execution.StepExecutionStage.<init>(StepExecutionStage.java:34)
	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:39)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
	at com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
	at com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
Failed: Vowels in English language are "aeiou".
Filename: .../basic4/specs/example.spec:10
Message: Connection closed [127.0.0.1:49447] cause: EOF


Failed: AfterStep hook for step: Vowels in English language are "aeiou".
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection


Failed: After Scenario
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection


Failed: After Specification
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection


Failed: After Suite
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection
```
**Steps to replicate**
* Create a `gauge-java` project
* Create an implementation of the custom parser at the same level as `StepImplementation.java`
```
import com.thoughtworks.gauge.execution.parameters.parsers.base.CustomParameterParser;
import gauge.messages.Spec;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class LocalDateGaugeParser extends CustomParameterParser<LocalDate> {

    @Override
    public boolean canParse(Class<?> aClass, Spec.Parameter parameter) {
        return aClass.equals(LocalDate.class);
    }

    @Override
    protected LocalDate customParse(Class<?> aClass, Spec.Parameter parameter) {
        DateTimeFormatter f = DateTimeFormatter.ofPattern("MM dd, yyyy");
        return LocalDate.from(f.parse(parameter.getValue()));
    }
}
```
* Use this in a step `something with date "03 04,2018"`
* Give the implementation for the step
```
    @Step("something with date <date>")
    public void implementation1(java.time.LocalDate date) {
        System.out.println(date);
    }
```
* Run the spec
> The above exception occurs

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-11
Commit Hash: 4d314ef

Plugins
-------
html-report (4.0.4.nightly-2018-03-30)
java (0.6.7.nightly-2018-04-06)
js (2.2.0.nightly-2018-04-12)
python (0.3.0.nightly-2018-04-10)
report-seed (0.0.1)
ruby (0.5.0.nightly-2018-04-11)
screenshot (0.0.1)
```

_Copied from original issue: getgauge/gauge-ruby#67_

**Comment by jackperalta** [comment]
for me the issue is rather that the example spec implemtation is in the default package.

From a Java perspective - locating implementations inside the default package is more problematic than helpsome

see
https://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice
https://www.quora.com/Why-does-Eclipse-discourage-the-use-of-the-default-package
 
etc

so for me the underlying issue is that the default step implementation is residing in the default package.

**Comment by sguptatw** [comment]
@jackperalta

Currently to check if it is a GaugeParser the package name is being compared. 
```
    private boolean isNotGaugeParser(Class<? extends ParameterParser> clazz) {
        return !clazz.getPackage().getName().equals("com.thoughtworks.gauge.execution.parameters.parsers.types");
    }
```
**Current behavior**
This restricts the package name that can be used for the custom parser. 

**Expected behavior**
I should be able to have the user custom package name for the parser I have defined. As long as it implements the `CustomParameterParser` defined in Gauge, it should work.

**Comment by sguptatw** [comment]
Updating the issue to ` the package name used for custom parser should not be restricted` instead of `Should be able to implement a parser in the default package`

**Comment by jackperalta** [comment]
@sguptatw 
the code line for `isNotGaugeParser` makes sure that the internal Gauge parsers are not loaded, when custom parsers are loaded. The line itself does not force a custum parser to be in a specific package.

Though it contains the problem for the NPE, as classes in the default package, do not have a package. So this would be the simple fix, which i mention befored.

But see my updated comment before. Even with that fix a custom parser would not be loaded when in a default package - and this is why I raise the issue of putting things into the default package at all

**Comment by sguptatw** [comment]
@jackperalta 

Doesn't getSubTypesOf(CustomParameterParser.class) take care of not loading Gauge Parsers. Unlike CustomParameterParsers `Gauge Parsers implement ParameterParser`

**Comment by jackperalta** [comment]
oh yes you are right - nice catch. The line is an artifact, before I introduced the custom parser class.

Pull Request is incoming for this
