### ISSUE TITLE
All the steps in spec files and concepts are showing as not implemented steps

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#156]
### Expected behavior
If there are step implementations for the steps, those steps in spec files and concepts should be showing as implemented steps.

### Actual behavior
All the steps in spec files and concepts are showing as not implemented steps.

### Steps to reproduce
1. In IntelliJ IDEA, it is giving an exception in plugin Gauge once the project is imported. 
2. So that all the steps in spec files and concepts are showing as not implemented steps. But can be executed.
3. **The error message is:** `com.intellij.openapi.module.impl.ModuleManagerComponent@f96fbf3: Gauge API not started`

**Details:**
```
com.intellij.openapi.module.impl.ModuleManagerComponent@f96fbf3: Gauge API not started
java.lang.RuntimeException: Gauge API not started
at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:76)
at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
at com.thoughtworks.gauge.connection.GaugeConnection.<init>(GaugeConnection.java:49)
at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:81)
at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:74)
at com.thoughtworks.gauge.module.lib.AbstractLibHelper.<init>(AbstractLibHelper.java:37)
at com.thoughtworks.gauge.module.lib.LibHelperFactory$GaugeModuleLibHelper.<init>(LibHelperFactory.java:43)
at com.thoughtworks.gauge.module.lib.LibHelperFactory.helperFor(LibHelperFactory.java:33)
at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:62)
at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:206)
at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$fireModuleAddedInWriteAction$4(ModuleManagerImpl.java:622)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:620)
at com.intellij.openapi.module.impl.ModuleManagerComponent.lambda$fireModulesAdded$0(ModuleManagerComponent.java:151)
at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:151)
at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:100)
at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:792)
at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:401)
at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:165)
at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
at java.awt.EventQueue.access$500(EventQueue.java:98)
at java.awt.EventQueue$3.run(EventQueue.java:715)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
```

### Gauge version
```
Gauge version: 0.9.8
Commit Hash: c23df9f

Plugins
-------
csharp (0.10.3)
flash (0.0.1)
html-report (4.0.4)
java (0.6.7)
json-report (0.2.1)
ruby (0.5.0)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

### IntelliJ IDEA Community version
```
IntelliJ IDEA 2018.1.3 (Community Edition)
Build #IC-181.4892.42, built on May 8, 2018
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

### Gauge plugin version
```
0.3.11
```

**Comment by NivedhaSenthil** [comment]
@osandadeshan can you share the contents in api.log and gauge.log in the logs folder in the project  ?

**Comment by osandadeshan** [comment]
@NivedhaSenthil 
Please find the contents in log folder in here.
[logs.zip](https://github.com/getgauge/gauge-java/files/2025142/logs.zip)

**Comment by NivedhaSenthil** [comment]
Unable to replicate the issue.

**Comment by sriv** [comment]
@osandadeshan - is this still an issue?

**Comment by Apoorva-GA** [comment]
Closing the issue.
Feel free to reopen if you are still facing the issue.
