### ISSUE TITLE
Dollar sign character not usable in data-tables

### ISSUE THREAD

**Issue by walto140** [getgauge/gauge-java#179]
The Dollar sign character, $,  should be able to be used in data-tables, but is causing an error when the spec is attempting to run. 

Looks to be from the intialization of StepDetails when the DynamicText is getting set. 

### Expected behavior
Any text/character should be able to be passed in from a data table

### Actual behavior
When the Dollar sign symbol, '$', is used in a data-table column an IllegalArgumentException is thrown 

`java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at java.util.regex.Matcher.replaceFirst(Matcher.java:1004)
	at com.thoughtworks.gauge.execution.parameters.DynamicParametersReplacer.findAndReplacePlaceholder(DynamicParametersReplacer.java:35)
	at com.thoughtworks.gauge.execution.parameters.DynamicParametersReplacer.replacePlaceholders(DynamicParametersReplacer.java:25)
	at com.thoughtworks.gauge.execution.ExecutionInfoMapper.stepFrom(ExecutionInfoMapper.java:59)
	at com.thoughtworks.gauge.execution.ExecutionInfoMapper.executionInfoFrom(ExecutionInfoMapper.java:34)
	at com.thoughtworks.gauge.processor.StepExecutionStartingProcessor.process(StepExecutionStartingProcessor.java:34)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:92)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:96)
	at com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:79)
	at java.lang.Thread.run(Thread.java:748)`

### Steps to reproduce
1. Install 0.6.9.nightly build of gauge-java
2. Run gauge init java
3. In example.spec add in a data-table, put in the $ character into a row, and reference the column in one of the steps
4. Run the spec.

### Gauge version
```
Gauge version: 1.0.1
Commit Hash: da2676b

Plugins
-------
html-report (4.0.5)
java (0.6.9.nightly-2018-09-04)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sguptatw** [comment]
**Findings**
This occurs only with the special character `$`.

With the following spec and implementation
```
# Specification Heading

|Something|
|---------|
|!@#%^&*()__-++~`"':;?/<>.,\\\||


## Print on console
* print the input <Something>
```
Implementation
```
    @Step("print the input <Something>")
    public void implementation1(Object arg0) {
        System.out.println(arg0);
    }
```
We do not get an exception. However when '$' is added getting the exception mentioned in the original issue
```
# Specification Heading

|Something|
|---------|
|!@#%^&*()__-++~`"':;?/<>.,\\\|$|

## Print on console
* print the input <Something>
```
