### ISSUE TITLE
Step implementations are showing as not implemented steps

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#184]
### Expected behavior
When open the IntelliJ IDEA, all the steps should show as implemented steps.

### Actual behavior
When open the IntelliJ IDEA, all the steps are showing as not implemented steps.

### Steps to reproduce
1. Open a Gauge java maven project in IntelliJ IDEA
2. You can see all the steps are showing as not implemented steps.

### Errors
**Comments:** 
`com.intellij.openapi.module.impl.ModuleManagerComponent@4ce80776: Gauge API not started`

**Details:**
```
com.intellij.openapi.module.impl.ModuleManagerComponent@4ce80776: Gauge API not started
java.lang.RuntimeException: Gauge API not started
	at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:76)
	at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
	at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
	at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
	at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
	at com.thoughtworks.gauge.connection.GaugeConnection.createConnection(GaugeConnection.java:87)
	at com.thoughtworks.gauge.connection.GaugeConnection.<init>(GaugeConnection.java:49)
	at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:81)
	at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:74)
	at com.thoughtworks.gauge.module.lib.AbstractLibHelper.<init>(AbstractLibHelper.java:37)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory$GaugeModuleLibHelper.<init>(LibHelperFactory.java:43)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory.helperFor(LibHelperFactory.java:33)
	at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:62)
	at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:204)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$fireModuleAddedInWriteAction$4(ModuleManagerImpl.java:624)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:622)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.lambda$fireModulesAdded$1(ModuleManagerComponent.java:144)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:144)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:97)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:771)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:165)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:869)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:215)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:579)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runSynchronously(CoreProgressManager.java:318)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:303)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:192)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:479)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:191)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:63)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:677)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:719)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy46.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:361)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:359)
	at com.intellij.idea.IdeaApplication.lambda$run$0(IdeaApplication.java:199)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:199)
	at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Screenshots
![capture](https://user-images.githubusercontent.com/9147189/46392865-8334c080-c700-11e8-8b69-257107f5467e.PNG)

### Gauge version
```
Gauge version: 1.0.1.nightly-2018-07-12
Commit Hash: ef40517

Plugins
-------
flash (0.0.1)
html-report (4.0.4)
java (0.6.8)
json-report (0.2.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.0)
```

### IntelliJ Gauge Plugin
Version: 0.3.12

**Comment by sguptatw** [comment]
@osandadeshan 

Kindly ensure the pom file of your project uses latest gauge-java and gauge-maven-plugin. 
```
        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>0.6.8</version>
        </dependency>
...
             <groupId>com.thoughtworks.gauge.maven</groupId>
             <artifactId>gauge-maven-plugin</artifactId>
             <version>1.3.3</version>
```

Things work as expected 
![maxsoft-ata](https://user-images.githubusercontent.com/6310197/46396074-f7c12c80-c70b-11e8-9555-c59380eb9dd8.png)

with Version
```
Gauge version: 1.0.3.nightly-2018-10-01
Commit Hash: 15b1e26

            <artifactId>gauge-java</artifactId>
            <version>0.6.8</version>

             <artifactId>gauge-maven-plugin</artifactId>
             <version>1.3.3</version>

Gauge-IntelliJ Version: 0.3.13.nightly-2018-09-14
```

Kindly let us know if you face any issues after upgrading to the mentioned versions

**Comment by osandadeshan** [comment]
@sguptatw 
I have updated Gauge and its plugins. But still some of the step implementations are showing as not implemented steps.
![capture](https://user-images.githubusercontent.com/9147189/46421998-03831200-c751-11e8-9135-c87042a0ffa3.PNG)

**Comment by osandadeshan** [comment]
@sguptatw 
I am facing the similar issue in Mac also.
MacOS Sierra
Version 10.12.6

**Comment by sguptatw** [comment]
Able to replicate the issue with IntelliJ version
```
IntelliJ IDEA 2018.2.4 (Community Edition)
Build #IC-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by sguptatw** [comment]
Here is a workaround. 
- Delete the iml and .idea files of the project. 
- Open the .pom file from IntelliJ -> Open as a project and proceed. 
> Gauge IDE features work.

**Comment by osandadeshan** [comment]
I have tried it. But still the same issue.

**Comment by hiruniii** [comment]
Try this [solution](https://docsgaugeorg.readthedocs.io/en/master/troubleshooting.html#steps-marked-as-unimplemented) given in gauge documentation

**Comment by chadlwilson** [comment]
Aside from earlier suggestions I'm going to clos ethics now, as the intellij plugin is maintained by Jetbrains for now, as I understand.

Can re-open if this is still an issue traced to Gauge itself.
