### ISSUE TITLE
Getting an exception when renaming

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#202]
**Expected behavior**
Should be able to rename a step seamlessly

**Actual behavior**
Getting an exception sometimes
```
o.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7c7a8dd4
java.lang.NullPointerException
	at com.thoughtworks.gauge.registry.StepRegistry.removeSteps(StepRegistry.java:78)
	at com.thoughtworks.gauge.scan.StaticScanner.removeSteps(StaticScanner.java:47)
	at com.thoughtworks.gauge.scan.StaticScanner.reloadSteps(StaticScanner.java:42)
	at com.thoughtworks.gauge.processor.CacheFileRequestProcessor.process(CacheFileRequestProcessor.java:37)
	at com.thoughtworks.gauge.LspServer.cacheFile(LspServer.java:51)
	at gauge.messages.lspServiceGrpc$MethodHandlers.invoke(lspServiceGrpc.java:793)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to replicate**
* Create a gauge-java project
* Rename a step
> Sometimes I am getting the above exception

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-03
Commit Hash: 62a48e5

Plugins
-------
java (0.7.0.nightly-2018-12-04)
```
> Blocks https://github.com/getgauge/gauge-vscode/issues/83

**Comment by sguptatw** [comment]
Verified with version
```
Gauge version: 1.0.4.nightly-2018-12-25
Commit Hash: fe5e7da

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0.nightly-2018-12-28)
```
