### ISSUE TITLE
Exception thrown without meaingful message if src directory is not present

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge-java#21]
When gauge tries to build the java project, if the **src** directory is not present or any of the directories mentioned under gauge_custom_compile_directory property then the below exception is thrown.
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xa code=0x2 addr=0x14 pc=0x5bec]

goroutine 1 [running]:
main.func·004(0x235450, 0x3, 0x0, 0x0, 0x511e98, 0x11136980, 0x0, 0x0)
	/Applications/Go Agent.app/pipelines/Gauge-Java/tmp/src/gauge-java/gauge-java.go:378 +0x16c
path/filepath.Walk(0x235450, 0x3, 0x1115ae84, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:392 +0x91
main.build(0x243938, 0x9, 0x1112e620, 0x6b)
	/Applications/Go Agent.app/pipelines/Gauge-Java/tmp/src/gauge-java/gauge-java.go:387 +0x53a
main.createClasspath(0x0, 0x0)
	/Applications/Go Agent.app/pipelines/Gauge-Java/tmp/src/gauge-java/gauge-java.go:327 +0x25d
main.startJava()
	/Applications/Go Agent.app/pipelines/Gauge-Java/tmp/src/gauge-java/gauge-java.go:81 +0x53
main.main()
	/Applications/Go Agent.app/pipelines/Gauge-Java/tmp/src/gauge-java/gauge-java.go:61 +0x30
````

A more meaningful error message should be displayed instead.

**Comment by kashishm** [comment]
Fixed in [commit](https://github.com/getgauge/gauge-java/commit/4a1cf046a01bfebb6d9ed3a847a3a4b4735cc5cc)
