### ISSUE TITLE
org.reflections.ReflectionsException: could not create class object from file META-INF/versions/9/module-info.class

### ISSUE THREAD

**Issue by rcaballeron** [getgauge/gauge-java#210]
### Expected behavior
It should execute the gauge test without any error

### Actual behavior
The test execution fails because of org.reflections.ReflectionsException

10:02:38.109 [main] DEBUG org.reflections.Reflections - could not scan file META-INF/versions/9/module-info.class in url file:/C:/Users/Roque/.m2/repository/net/bytebuddy/byte-buddy/1.9.5/byte-buddy-1.9.5.jar with scanner SubTypesScanner
org.reflections.ReflectionsException: could not create class object from file META-INF/versions/9/module-info.class
        at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
        at org.reflections.Reflections.scan(Reflections.java:253)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
        at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:66)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:41)
        at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:80)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:57)
Caused by: org.reflections.ReflectionsException: could not create class file from module-info.class
        at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
        at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
        at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
        ... 7 common frames omitted
Caused by: java.io.IOException: invalid constant type: 19 at 4
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1244)
        at javassist.bytecode.ConstPool.read(ConstPool.java:1175)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:185)
        at javassist.bytecode.ClassFile.read(ClassFile.java:829)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
        at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
        ... 9 common frames omitted
1

### Steps to reproduce
1. Create a basic spring web/rest boot project using Maven as building tool
2. Initialize gauge project
3. Run mvn package

### Steps to fix
Downgrade org.reflections dependency from version 0.9.11 to 0.9.10
```
         <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.10</version>
            <scope>test</scope>
        </dependency>
```

### Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.6)
java (0.6.9)
js (2.3.2)
screenshot (0.0.1)
```

**Comment by Apoorva-GA** [comment]
@rcaballeron Could you please share a simple project, where the issue can be replicated.

**Comment by rcaballeron** [comment]
@Apoorva-GA please find it attached.
[mygauge.zip](https://github.com/getgauge/gauge-java/files/2671884/mygauge.zip)

**Comment by Apoorva-GA** [comment]
@rcaballeron Thanks for sharing the sample project. I Could replicate the issue.

Looks like the error is due to ronmamo/reflections#171 and ronmamo/reflections#190.
Both the issues are currently open.

As you have mentioned, the workaround would be to downgrade `org.reflections` dependency to `0.9.10` until the open issues are fixed.

**Comment by Apoorva-GA** [comment]
Closing this for now. Feel free to get back if you face any issue in future.
