### ISSUE TITLE
Should not get connection error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#211]
**Expected behavior**
Should be able to run tests without failure

**Actual behavior**
Getting exception
```
Error: Connection is closed.
    at new ConnectionError (/godata/pipelines/Java-LSP-Tests/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/godata/pipelines/Java-LSP-Tests/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendRequest (/godata/pipelines/Java-LSP-Tests/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at Object.sendRequest (/godata/pipelines/Java-LSP-Tests/tests/lsp/rpc/request.js:9:23)
    at Object.shutDown (/godata/pipelines/Java-LSP-Tests/tests/lsp/languageclient.js:20:20)
    at Object.<anonymous> (/godata/pipelines/Java-LSP-Tests/tests/project.js:31:30)
    at Test.runFn (/home/go/.gauge/plugins/js/2.3.4.nightly-2018-12-04/src/test.js:68:23)
    at Test.run (/home/go/.gauge/plugins/js/2.3.4.nightly-2018-12-04/src/test.js:105:11)
    at Object.executeStep [as step] (/home/go/.gauge/plugins/js/2.3.4.nightly-2018-12-04/src/executor.js:49:42)
    at MessageProcessor.executeStep (/home/go/.gauge/plugins/js/2.3.4.nightly-2018-12-04/src/message-processor.js:48:26)
```
**Steps to replicate**
* Run the LSP tests for java on Linux
`gauge run specs --env=java-wd`
> The above error occurs for 21 scenarios

**Version**
```
Gauge version: 1.0.4
Commit Hash: 149f3a5

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0)
js (2.3.4.nightly-2018-12-04)
```
> Blocks https://github.com/getgauge/gauge-vscode/issues/83

**Comment by sguptatw** [comment]
Java-LSP getting connection closed errors in the no-working directory mode https://build.gauge.org/go/tab/build/detail/Java-LSP-Tests/42/no-wd/1/linux

**Comment by Apoorva-GA** [comment]
Not happening anymore on linux.
