### ISSUE TITLE
Execution fails even if validation is successful, when Implementation file is outside src

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-java#228]
### Expected behavior
If a project is validated successfully should be able to run successfully as well

### Actual behavior
The project validation is successful, but the execution fails with an exception
```
java.lang.NullPointerException
	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:45)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:93)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:116)
	at com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:99)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
### Steps to reproduce
1. `gauge init java`
2. `mv src/test/java/StepImplementation.java ./`
3. `gauge validate specs`
4. `gauge run specs`

## Note
1. The validation output is 
```
Invalid message type received KillProcessRequest
No errors found.
```
the exit code is 0

2. The property `gauge_custom_compile_dir` should be taken care.

### Gauge version
```
auge version: 1.0.4
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.6)
java (0.7.0)
```

**Comment by Debashis9012** [comment]
Its working fine. Checked with  the below version

```
0.7.0.nightly-2019-01-24

```
