### ISSUE TITLE
ClasspathScanner throwing warnings

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge-java#34]
Reported by @henkbl at https://github.com/getgauge/gauge/issues/228 and @vshanve at https://github.com/getgauge/gauge/issues/222.

Stacktrace:
```
09:17:26.196 [INFO] 1 [main] WARN org.reflections.Reflections - could not create Dir using com.thoughtworks.gauge.scan.ClasspathScanner$1@49b96230 from url file:/Users/.gauge/plugins/java/0.3.1/. skipping.
java.lang.NullPointerException
at com.thoughtworks.gauge.scan.ClasspathScanner$1.createDir(ClasspathScanner.java:53)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
at org.reflections.Reflections.scan(Reflections.java:237)
at org.reflections.Reflections.scan(Reflections.java:204)
at org.reflections.Reflections.(Reflections.java:129)
at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
09:17:26.196 [INFO] 3 [main] WARN org.reflections.Reflections - could not create Dir using directory from url file:/Users/.gauge/plugins/java/0.3.1/. skipping.
java.lang.NullPointerException
at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:239)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:98)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
at org.reflections.Reflections.scan(Reflections.java:237)
at org.reflections.Reflections.scan(Reflections.java:204)
at org.reflections.Reflections.(Reflections.java:129)
at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
09:17:26.196 [INFO] 3 [main] WARN org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/.gauge/plugins/java/0.3.1/*]
either use fromURL(final URL url, final List urlTypes) or use the static setDefaultURLTypes(final List urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
at org.reflections.Reflections.scan(Reflections.java:237)
at org.reflections.Reflections.scan(Reflections.java:204)
at org.reflections.Reflections.(Reflections.java:129)
at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
09:17:26.687 [INFO] java.net.SocketException: Connection reset
09:17:26.687 [INFO] at java.net.SocketInputStream.read(SocketInputStream.java:196)
at java.net.SocketInputStream.read(SocketInputStream.java:122)
09:17:26.687 [INFO] at com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1121)
09:17:26.687 [INFO] at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1081)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:1149)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.google.protobuf.CodedInputStream.readRawVarint64SlowPath(CodedInputStream.java:778)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.google.protobuf.CodedInputStream.readRawVarint64(CodedInputStream.java:770)
09:17:26.687 [INFO] at com.thoughtworks.gauge.connection.GaugeConnection.getMessageLength(GaugeConnection.java:51)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.thoughtworks.gauge.connection.GaugeConnection.getAPIResponse(GaugeConnection.java:150)
09:17:26.687 [INFO] at com.thoughtworks.gauge.connection.GaugeConnection.getStepValue(GaugeConnection.java:190)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.thoughtworks.gauge.connection.GaugeConnection.getStepValue(GaugeConnection.java:176)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:47)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:39)
09:17:26.687 [INFO] 
09:17:26.687 [INFO] at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:39)
09:17:26.687 [INFO] at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
09:17:26.687 [INFO] 
09:17:26.688 [INFO] Exception in thread "main" java.lang.NullPointerException
09:17:26.688 [INFO] at com.thoughtworks.gauge.registry.StepRegistry.addStepImplementation(StepRegistry.java:29)
09:17:26.688 [INFO] at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:48)
09:17:26.688 [INFO] at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:39)
09:17:26.688 [INFO] at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:39)
09:17:26.688 [INFO] 
09:17:26.688 [INFO] at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
```

**Comment by mahendrakariya** [comment]
It's quite possible that reflections utility is unable to create new directories because of the upper limit set on file descriptors by the OS. We need to verify this. If this is not the case, we need to look into what is causing this issue.

Refer getgauge/gauge#222 for detailed discussion.

**Comment by mahendrakariya** [comment]
Nobody has reported this issue for more than a year. Looks like increasing the upper limit is the solution.

**Comment by MichaelMcKavanagh** [comment]
This still happens, and I'm pretty sure it has nothing to do with upper limit of file descriptors

[2017-05-25 04:22:10:519] [main] WARN Reflections - could not create Dir using com.thoughtworks.gauge.scan.ClasspathScanner$1@123772c4 from url file:/root/.gauge/plugins/java/0.5.1/*. skipping.
java.lang.NullPointerException
	at com.thoughtworks.gauge.scan.ClasspathScanner$1.createDir(ClasspathScanner.java:53)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:237)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)

**Comment by sriv** [comment]
Your logs indicate that you are on gauge-java `0.5.1`:
```
/root/.gauge/plugins/java/0.5.1/*
```
The latest version of gauge-java is `0.6.3` and gauge is `0.8.4`.

Could you please try doing and upgrade and check? Thanks.

**Comment by MichaelMcKavanagh** [comment]
Not sure why the logs are saying that because without changing anything and checking:

$gauge --version

Gauge version: 0.8.3

Plugins
-------
html-report (3.1.0)
java (0.6.2)
xml-report (0.2.0)

**Comment by sriv** [comment]
My guess is that your project has a dependency on gauge-java `0.5.1`. If you are using maven/gradle, please check your `pom.xml` or `build.gradle` to see if the `gauge-java` dependency is locked down to `0.5.1`.
