### ISSUE TITLE
MacOS - java.util.MissingFormatArgumentException: Format specifier '%s'

### ISSUE THREAD

**Issue by sudhindra-aithal** [getgauge/gauge-java#380]
Format specifier '%s'
java.util.MissingFormatArgumentException: Format specifier '%s'
at java.base/java.util.Formatter.format(Formatter.java:2672)
at java.base/java.util.Formatter.format(Formatter.java:2609)
at java.base/java.lang.String.format(String.java:3274)
at com.thoughtworks.gauge.connection.GaugeConnector.connect(GaugeConnector.java:45)
at com.thoughtworks.gauge.connection.GaugeConnector.makeConnectionsToGaugeCore(GaugeConnector.java:35)
at com.thoughtworks.gauge.GaugeRuntime.makeConnection(GaugeRuntime.java:120)
at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:106)
at com.thoughtworks.gauge.GaugeRuntime.startGaugeServer(GaugeRuntime.java:76)
at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:53)

### Expected behavior
Gauge API should start

### Actual behavior
Gauge API is not starting

### Steps to reproduce
Try to run script on Mac OS (13.x)

### Gauge version
```
Gauge version: 1.0.7
Plugins

html-report (4.0.9)
java (0.7.4)
screenshot (0.0.1)

**Comment by sudhindra-aithal** [comment]
Upgrading plugin java version and pom xml, fixed the issue
