### ISSUE TITLE
NullPointerException when running tests in parallel (0.7.9) 

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge-java#482]
### Actual behavior

When running the tests in parallel with `enable_multithreading=true`.

```sh
Error ----------------------------------

[java]
Error in thread 20
null
java.lang.NullPointerException
        at com.thoughtworks.gauge.registry.StepRegistry.addStepImplementation(StepRegistry.java:35)
        at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:46)
        at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:33)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:35)
        at com.thoughtworks.gauge.connection.MessageProcessorFactory.getProcessor(MessageProcessorFactory.java:61)
        at com.thoughtworks.gauge.RunnerServiceHandler.lambda$initializeSpecDataStore$2(RunnerServiceHandler.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[java]
Error in thread 22
null
java.lang.NullPointerException
        at com.thoughtworks.gauge.registry.StepRegistry.addStepImplementation(StepRegistry.java:35)
        at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:46)
        at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:33)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:35)
        at com.thoughtworks.gauge.connection.MessageProcessorFactory.getProcessor(MessageProcessorFactory.java:61)
        at com.thoughtworks.gauge.RunnerServiceHandler.lambda$initializeSpecDataStore$2(RunnerServiceHandler.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[Gauge]
java runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

[Gauge]
java runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
        darwin, 1.1.1
        flash (0.0.2), html-report (4.0.11), java (0.7.9), json-report (0.3.3), reportportal (1.7.0), reportserver (0.2.0), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.3)
```

And this in middle of the run 

```sh
Error in thread 15
null
java.lang.NullPointerException
        at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:35)
        at com.thoughtworks.gauge.RunnerServiceHandler.lambda$executeStep$7(RunnerServiceHandler.java:166)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[Gauge]
java runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

[Gauge]
java runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
        darwin, 1.1.1
        flash (0.0.2), html-report (4.0.11), java (0.7.9), json-report (0.3.3), reportportal (1.7.0), reportserver (0.2.0), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.3)
Error ----------------------------------

[java]
Error in thread 15
null
java.lang.NullPointerException
        at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:35)
        at com.thoughtworks.gauge.RunnerServiceHandler.lambda$executeStep$7(RunnerServiceHandler.java:166)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[Gauge]
java runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
        darwin, 1.1.1
        flash (0.0.2), html-report (4.0.11), java (0.7.9), json-report (0.3.3), reportportal (1.7.0), reportserver (0.2.0), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.3)
```

See conversation in https://github.com/getgauge/gauge-java/issues/455

### Gauge version
```
        darwin, 1.1.1
        flash (0.0.2), html-report (4.0.11), java (0.7.9), json-report (0.3.3), reportportal (1.7.0), reportserver (0.2.0), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.3)
```

**Comment by sriv** [comment]
Something does not add up @haroon-sheikh , if you see this stacktrace snippet that you posted:

```
java.lang.NullPointerException
        at com.thoughtworks.gauge.registry.StepRegistry.addStepImplementation(StepRegistry.java:35)
        at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:46)
        at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:33)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:35)
        at com.thoughtworks.gauge.connection.MessageProcessorFactory.getProcessor(MessageProcessorFactory.java:61)
        at com.thoughtworks.gauge.RunnerServiceHandler.lambda$initializeSpecDataStore$2(RunnerServiceHandler.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

and if you follow the stacktrace against [`0.7.9`](https://github.com/getgauge/gauge-java/tree/v0.7.9): 

- `StepsScanner.buildStepRegistry(StepsScanner.java:46)` does not invoke `StepRegistry.addStepImplementation`
- instead `buildStepRegistry` method invokes a private method [`addExternalStepEntryToRegistry`](https://github.com/getgauge/gauge-java/blob/v0.7.9/src/main/java/com/thoughtworks/gauge/scan/StepsScanner.java#L50-L53) which is missinng in the stacktrace.

I suspect the versions reported and the jar loaded are not in sync. Could you please try in a fresh machine, perhaps a docker container, where you don't share the MAVEN_HOME folder, thus forcing a fresh setup?

**Comment by haroon-sheikh** [comment]
I've just this in a docker container and now i'm seeing a different issue mentioned here https://github.com/getgauge/gauge/issues/1629#issuecomment-661272065

**Comment by BugDiver** [comment]
@haroon-sheikh Can you please validate that things are working fine with the latest releases of Gauge and Gauge-java?

**Comment by haroon-sheikh** [comment]
@BugDiver Have tested with versions below, and I'm not able to reproduce it anymore.

```
Gauge version: 1.1.3
Plugins
-------
html-report (4.0.12)
java (0.7.9)
screenshot (0.0.1)
```

Happy for you to close the issue. We can always reopen it if it appears again.
