### ISSUE TITLE
Getting "... could not create Dir... " when executing specs

### ISSUE THREAD

**Issue by henkeja** [getgauge/gauge-java#57]
When executing specs I'm getting the following warnings, these occur on the command line or in Idea:

0    [main] WARN  org.reflections.Reflections  - could not create Dir using com.thoughtworks.gauge.scan.ClasspathScanner$1@ef52dd from url file:/C:/Users/henkja/AppData/R
oaming/gauge/plugins/java/0.4.0/*. skipping.
java.lang.NullPointerException
        at com.thoughtworks.gauge.scan.ClasspathScanner$1.createDir(ClasspathScanner.java:53)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
7    [main] WARN  org.reflections.Reflections  - could not create Dir using directory from url file:/C:/Users/henkja/AppData/Roaming/gauge/plugins/java/0.4.0/*. skipping.

java.lang.NullPointerException
        at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:239)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:98)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
8    [main] WARN  org.reflections.Reflections  - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/C:/Users/henkja/AppData/Roaming/gauge/plugins/java/0.4.0/*]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType)
with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)

The specs run just fine, I'm getting the results I'm expecting, it's just a lot of noise showing up on each run that I don't need or want to see.

I have tried uninstalling and reinstalling the Java plugin and that did not do anything.

### Gauge version

    Gauge IntelliJ plugin Version: 0.1.0
    Gauge version: 0.4.0

Plugins:
html-report (2.1.0)
java (0.4.0)

**Comment by henkeja** [comment]
In doing some review of the code, I noticed that something had changed the Java version from 1.7.0_76 to 1.8.0_91. When I changed it back to Java 7 the error went away.

**Comment by mahendrakariya** [comment]
I am closing this issue as it has been resolved.
