### ISSUE TITLE
Unable to debug specs with gauge-java starting with version 0.7.8

### ISSUE THREAD

**Issue by 0vid1u** [getgauge/gauge-java#619]
**Describe the bug**
Get `Failed to start gauge API: Timed out connecting to java` each time when try to debug a spec using gauge java version 0.7.8 till to latest version 0.7.15 in Intellij IDEA.

**Using the gauge-java version 0.7.7 it works as expected.** 

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialize a gauge+maven+selenium project
2. Try to debug a spec
3. See error

```
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console C:/Workspace/SANDBOX/gauge-selenium-maven/specs/example.spec
Testing started at 5:31 PM ...
Runner Ready for Debugging
Listening for transport dt_socket at address: 51544
Error ----------------------------------

[Gauge]
Failed to start gauge API: Timed out connecting to java

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	windows, 1.4.0, 5cc544c
	html-report (4.1.0), java (0.7.8), reportportal (1.12.0), screenshot (0.1.0), spectacle (0.1.4)


Process finished with exit code 1

```

**Logs**

gauge.log
```
28-07-2021 17:42:35.334 [Gauge] [DEBUG] Created gauge_screenshots_dir at C:\Workspace\SANDBOX\gauge-selenium-maven\.gauge\screenshots
28-07-2021 17:42:35.338 [Gauge] [DEBUG] Plugin java is already installed.
28-07-2021 17:42:35.339 [Gauge] [DEBUG] Plugin html-report is already installed.
28-07-2021 17:42:35.340 [Gauge] [DEBUG] Parsing started.
28-07-2021 17:42:35.340 [Gauge] [DEBUG] Started concepts parsing.
28-07-2021 17:42:35.348 [Gauge] [DEBUG] 0 concepts parsing completed.
28-07-2021 17:42:35.348 [Gauge] [DEBUG] Started specifications parsing.
28-07-2021 17:42:35.349 [Gauge] [DEBUG] 1 specifications parsing completed.
28-07-2021 17:42:35.349 [Gauge] [DEBUG] Parsing completed.
28-07-2021 17:42:36.020 [Gauge] [DEBUG] Checking updates...
28-07-2021 17:42:36.025 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,reportportal,screenshot,spectacle&o=windows&a=amd64
28-07-2021 17:42:36.378 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,reportportal,screenshot,spectacle&o=windows&a=amd64
28-07-2021 17:42:36.510 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/reportportal?l=java&p=html-report,java,reportportal,screenshot,spectacle&o=windows&a=amd64
28-07-2021 17:42:36.689 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,reportportal,screenshot,spectacle&o=windows&a=amd64
28-07-2021 17:42:36.857 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/spectacle?l=java&p=html-report,java,reportportal,screenshot,spectacle&o=windows&a=amd64
28-07-2021 17:42:47.875 [java] [INFO] Runner Ready for Debugging
28-07-2021 17:42:48.604 [java] [INFO] Listening for transport dt_socket at address: 60747
28-07-2021 17:43:05.375 [Gauge] [CRITICAL] Failed to start gauge API: Timed out connecting to java

```

**Expected behavior**
Expect to break the execution on breakpoint.

**Versions:**

windows, 1.4.0, 5cc544c
html-report (4.1.0), java (0.7.8), reportportal (1.12.0), screenshot (0.1.0), spectacle (0.1.4)

 - Java version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

 - Maven/Gradle version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

```
gauge -v

Gauge version: 1.4.0
Commit Hash: 5cc544c

Plugins
-------
html-report (4.1.0)
java (0.7.8)
reportportal (1.12.0)
screenshot (0.1.0)
spectacle (0.1.4)

```

**Additional context**

**Comment by KartikPhrael** [comment]
We are also facing this issue. All of us will really appreciate it if you guys can prioritize this please !

**Comment by sriv** [comment]
@0vid1u @KartikPhrael - can you try and see if debugging works on vscode with gauge,java plugins installed?

Also, in the `logs` folder, do you see any further details? Is there an `api.log` and does that have any details? There may also be `.out` files that contain the output from the java process.

I tried creating a new gauge+java project and I am able to run debug fine. Here's my current gauge version on windows:

```
Gauge version: 1.2.1
Commit Hash: 5a3ffeae

Plugins
-------
dotnet (0.3.1)
html-report (4.0.12)
java (0.7.15)
js (2.3.17)
json-report (0.3.6)
screenshot (0.0.1)
xml-report (0.2.4)
```

**Comment by 0vid1u** [comment]
Hi @sriv ,

I have tried to debug with vs-code, looks like it works...
![image](https://user-images.githubusercontent.com/2903146/127650422-d11ef220-84bd-4656-8775-32a6dc69b8e7.png)

IntelliJ doesn't want to start debugging and show timeout connecting java.

Attached generated logs:
gauge.log
-----------
30-07-2021 15:12:21.189 [Gauge] [DEBUG] Created gauge_screenshots_dir at C:\Workspace\SANDBOX\gauge-selenium-maven\.gauge\screenshots
30-07-2021 15:12:21.195 [Gauge] [DEBUG] Plugin java is already installed.
30-07-2021 15:12:21.196 [Gauge] [DEBUG] Plugin html-report is already installed.
30-07-2021 15:12:21.198 [Gauge] [DEBUG] Parsing started.
30-07-2021 15:12:21.198 [Gauge] [DEBUG] Started concepts parsing.
30-07-2021 15:12:21.210 [Gauge] [DEBUG] 0 concepts parsing completed.
30-07-2021 15:12:21.211 [Gauge] [DEBUG] Started specifications parsing.
30-07-2021 15:12:21.212 [Gauge] [DEBUG] 1 specifications parsing completed.
30-07-2021 15:12:21.213 [Gauge] [DEBUG] Parsing completed.
30-07-2021 15:12:21.594 [Gauge] [DEBUG] Checking updates...
30-07-2021 15:12:21.604 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,screenshot&o=windows&a=amd64
30-07-2021 15:12:21.674 [java] [DEBUG] ***** Printing Properties/Env Values *****
30-07-2021 15:12:21.674 [java] [DEBUG] PATH: C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Gauge\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Java\jdk-14.0.2\bin;C:\ProgramData\chocolatey\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\Azure Data Studio\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Gradle\gradle-7.1.1\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\PowerShell\7\;C:\Users\otuvrila\scoop\shims;C:\Program Files\RSA SecurID Token Common\;C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.4\bin;C:\Users\otuvrila\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\otuvrila\AppData\Local\GitHubDesktop\bin;C:\Users\otuvrila\.dotnet\tools;C:\Users\otuvrila\AppData\Local\Microsoft\WindowsApps;C:\Users\otuvrila\AppData\Roaming\gauge\plugins\screenshot\0.1.0
30-07-2021 15:12:21.674 [java] [DEBUG] JAVA_HOME: C:\Program Files\Java\jdk-14.0.2
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_project_root: C:\Workspace\SANDBOX\gauge-selenium-maven
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_parallel_streams_count: 8
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_reports_dir: reports
30-07-2021 15:12:21.675 [java] [DEBUG] overwrite_reports: true
30-07-2021 15:12:21.675 [java] [DEBUG] logs_directory: logs
30-07-2021 15:12:21.675 [java] [DEBUG] enable_multithreading: false
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_specs_dir: specs
30-07-2021 15:12:21.675 [java] [DEBUG] csv_delimiter: ,
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_java_home: 
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_custom_build_path: 
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_additional_libs: libs/*
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_jvm_args: 
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_custom_compile_dir: 
30-07-2021 15:12:21.675 [java] [DEBUG] gauge_clear_state_level: scenario
30-07-2021 15:12:21.675 [java] [DEBUG] ***** END *****
30-07-2021 15:12:22.014 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,screenshot&o=windows&a=amd64
30-07-2021 15:12:22.154 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,screenshot&o=windows&a=amd64
30-07-2021 15:12:32.723 [java] [DEBUG] classpath set to C:\Program Files\Java\jdk-14.0.2!\java.base;C:\Program Files\Java\jdk-14.0.2!\java.compiler;C:\Program Files\Java\jdk-14.0.2!\java.datatransfer;C:\Program Files\Java\jdk-14.0.2!\java.desktop;C:\Program Files\Java\jdk-14.0.2!\java.instrument;C:\Program Files\Java\jdk-14.0.2!\java.logging;C:\Program Files\Java\jdk-14.0.2!\java.management;C:\Program Files\Java\jdk-14.0.2!\java.management.rmi;C:\Program Files\Java\jdk-14.0.2!\java.naming;C:\Program Files\Java\jdk-14.0.2!\java.net.http;C:\Program Files\Java\jdk-14.0.2!\java.prefs;C:\Program Files\Java\jdk-14.0.2!\java.rmi;C:\Program Files\Java\jdk-14.0.2!\java.scripting;C:\Program Files\Java\jdk-14.0.2!\java.se;C:\Program Files\Java\jdk-14.0.2!\java.security.jgss;C:\Program Files\Java\jdk-14.0.2!\java.security.sasl;C:\Program Files\Java\jdk-14.0.2!\java.smartcardio;C:\Program Files\Java\jdk-14.0.2!\java.sql;C:\Program Files\Java\jdk-14.0.2!\java.sql.rowset;C:\Program Files\Java\jdk-14.0.2!\java.transaction.xa;C:\Program Files\Java\jdk-14.0.2!\java.xml;C:\Program Files\Java\jdk-14.0.2!\java.xml.crypto;C:\Program Files\Java\jdk-14.0.2!\jdk.accessibility;C:\Program Files\Java\jdk-14.0.2!\jdk.aot;C:\Program Files\Java\jdk-14.0.2!\jdk.attach;C:\Program Files\Java\jdk-14.0.2!\jdk.charsets;C:\Program Files\Java\jdk-14.0.2!\jdk.compiler;C:\Program Files\Java\jdk-14.0.2!\jdk.crypto.cryptoki;C:\Program Files\Java\jdk-14.0.2!\jdk.crypto.ec;C:\Program Files\Java\jdk-14.0.2!\jdk.crypto.mscapi;C:\Program Files\Java\jdk-14.0.2!\jdk.dynalink;C:\Program Files\Java\jdk-14.0.2!\jdk.editpad;C:\Program Files\Java\jdk-14.0.2!\jdk.hotspot.agent;C:\Program Files\Java\jdk-14.0.2!\jdk.httpserver;C:\Program Files\Java\jdk-14.0.2!\jdk.incubator.foreign;C:\Program Files\Java\jdk-14.0.2!\jdk.incubator.jpackage;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.ed;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.jvmstat;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.le;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.opt;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.vm.ci;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.vm.compiler;C:\Program Files\Java\jdk-14.0.2!\jdk.internal.vm.compiler.management;C:\Program Files\Java\jdk-14.0.2!\jdk.jartool;C:\Program Files\Java\jdk-14.0.2!\jdk.javadoc;C:\Program Files\Java\jdk-14.0.2!\jdk.jcmd;C:\Program Files\Java\jdk-14.0.2!\jdk.jconsole;C:\Program Files\Java\jdk-14.0.2!\jdk.jdeps;C:\Program Files\Java\jdk-14.0.2!\jdk.jdi;C:\Program Files\Java\jdk-14.0.2!\jdk.jdwp.agent;C:\Program Files\Java\jdk-14.0.2!\jdk.jfr;C:\Program Files\Java\jdk-14.0.2!\jdk.jlink;C:\Program Files\Java\jdk-14.0.2!\jdk.jshell;C:\Program Files\Java\jdk-14.0.2!\jdk.jsobject;C:\Program Files\Java\jdk-14.0.2!\jdk.jstatd;C:\Program Files\Java\jdk-14.0.2!\jdk.localedata;C:\Program Files\Java\jdk-14.0.2!\jdk.management;C:\Program Files\Java\jdk-14.0.2!\jdk.management.agent;C:\Program Files\Java\jdk-14.0.2!\jdk.management.jfr;C:\Program Files\Java\jdk-14.0.2!\jdk.naming.dns;C:\Program Files\Java\jdk-14.0.2!\jdk.naming.rmi;C:\Program Files\Java\jdk-14.0.2!\jdk.net;C:\Program Files\Java\jdk-14.0.2!\jdk.nio.mapmode;C:\Program Files\Java\jdk-14.0.2!\jdk.rmic;C:\Program Files\Java\jdk-14.0.2!\jdk.scripting.nashorn;C:\Program Files\Java\jdk-14.0.2!\jdk.scripting.nashorn.shell;C:\Program Files\Java\jdk-14.0.2!\jdk.sctp;C:\Program Files\Java\jdk-14.0.2!\jdk.security.auth;C:\Program Files\Java\jdk-14.0.2!\jdk.security.jgss;C:\Program Files\Java\jdk-14.0.2!\jdk.unsupported;C:\Program Files\Java\jdk-14.0.2!\jdk.unsupported.desktop;C:\Program Files\Java\jdk-14.0.2!\jdk.xml.dom;C:\Program Files\Java\jdk-14.0.2!\jdk.zipfs;C:\Workspace\SANDBOX\gauge-selenium-maven\target\test-classes;C:\Users\otuvrila\.m2\repository\com\thoughtworks\gauge\gauge-java\0.7.15\gauge-java-0.7.15.jar;C:\Users\otuvrila\.m2\repository\com\github\javaparser\javaparser-core\3.16.3\javaparser-core-3.16.3.jar;C:\Users\otuvrila\.m2\repository\commons-io\commons-io\2.8.0\commons-io-2.8.0.jar;C:\Users\otuvrila\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\otuvrila\.m2\repository\org\json\json\20210307\json-20210307.jar;C:\Users\otuvrila\.m2\repository\com\google\protobuf\protobuf-java\3.15.8\protobuf-java-3.15.8.jar;C:\Users\otuvrila\.m2\repository\com\google\guava\guava\30.1.1-jre\guava-30.1.1-jre.jar;C:\Users\otuvrila\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\otuvrila\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\otuvrila\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\otuvrila\.m2\repository\org\checkerframework\checker-qual\3.8.0\checker-qual-3.8.0.jar;C:\Users\otuvrila\.m2\repository\com\google\errorprone\error_prone_annotations\2.5.1\error_prone_annotations-2.5.1.jar;C:\Users\otuvrila\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-netty-shaded\1.37.0\grpc-netty-shaded-1.37.0.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-core\1.37.0\grpc-core-1.37.0.jar;C:\Users\otuvrila\.m2\repository\com\google\android\annotations\4.1.1.4\annotations-4.1.1.4.jar;C:\Users\otuvrila\.m2\repository\io\perfmark\perfmark-api\0.23.0\perfmark-api-0.23.0.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-protobuf\1.37.0\grpc-protobuf-1.37.0.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-api\1.37.0\grpc-api-1.37.0.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-context\1.37.0\grpc-context-1.37.0.jar;C:\Users\otuvrila\.m2\repository\com\google\api\grpc\proto-google-common-protos\2.0.1\proto-google-common-protos-2.0.1.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-protobuf-lite\1.37.0\grpc-protobuf-lite-1.37.0.jar;C:\Users\otuvrila\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.19\animal-sniffer-annotations-1.19.jar;C:\Users\otuvrila\.m2\repository\io\grpc\grpc-stub\1.37.0\grpc-stub-1.37.0.jar;C:\Users\otuvrila\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\otuvrila\.m2\repository\org\assertj\assertj-core\3.10.0\assertj-core-3.10.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-java\3.12.0\selenium-java-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-api\3.12.0\selenium-api-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.12.0\selenium-chrome-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.12.0\selenium-edge-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.12.0\selenium-firefox-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.12.0\selenium-ie-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.12.0\selenium-opera-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.12.0\selenium-remote-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.12.0\selenium-safari-driver-3.12.0.jar;C:\Users\otuvrila\.m2\repository\org\seleniumhq\selenium\selenium-support\3.12.0\selenium-support-3.12.0.jar;C:\Users\otuvrila\.m2\repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3.jar;C:\Users\otuvrila\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\otuvrila\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\otuvrila\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\otuvrila\.m2\repository\com\google\code\gson\gson\2.8.2\gson-2.8.2.jar;C:\Users\otuvrila\.m2\repository\org\apache\httpcomponents\httpclient\4.5.3\httpclient-4.5.3.jar;C:\Users\otuvrila\.m2\repository\org\apache\httpcomponents\httpcore\4.4.6\httpcore-4.4.6.jar;C:\Users\otuvrila\.m2\repository\com\squareup\okhttp3\okhttp\3.9.1\okhttp-3.9.1.jar;C:\Users\otuvrila\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar;C:\Users\otuvrila\.m2\repository\io\github\bonigarcia\webdrivermanager\3.7.1\webdrivermanager-3.7.1.jar;C:\Users\otuvrila\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\otuvrila\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\otuvrila\.m2\repository\org\rauschig\jarchivelib\1.0.0\jarchivelib-1.0.0.jar;C:\Users\otuvrila\.m2\repository\org\apache\commons\commons-compress\1.18\commons-compress-1.18.jar;C:\Users\otuvrila\.m2\repository\org\jsoup\jsoup\1.11.3\jsoup-1.11.3.jar;C:\Users\otuvrila\.m2\repository\org\reflections\reflections\0.9.10\reflections-0.9.10.jar;C:\Users\otuvrila\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar;C:\Users\otuvrila\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar
30-07-2021 15:12:32.826 [java] [DEBUG] found java executable in C:\Program Files\Java\jdk-14.0.2\bin\java.exe
30-07-2021 15:12:32.826 [java] [INFO] 
Runner Ready for Debugging
30-07-2021 15:12:32.826 [java] [DEBUG] running - C:\Program Files\Java\jdk-14.0.2\bin\java.exe [-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=49480,timeout=25000 -Dfile.encoding=UTF-8 com.thoughtworks.gauge.GaugeRuntime --start]
30-07-2021 15:12:32.826 [java] [DEBUG] stdout/stderr is logged to logs\18696-java.exe.out
30-07-2021 15:12:33.359 [java] [INFO] Listening for transport dt_socket at address: 49480
30-07-2021 15:12:51.452 [Gauge] [CRITICAL] Failed to start gauge API: Timed out connecting to java


18696-java.exe.out
---------------------
Listening for transport dt_socket at address: 49480

**Comment by osandadeshan** [comment]
Facing the same issue for a while. 
@zabil Appreciate it if you can prioritize a quick fix for this.

**Comment by jlc68** [comment]
We are facing the same issue after upgrading from 0.7.5 to 0.8.1

Here are additional logs that don't appear to be included above:
13-04-2022 08:54:37.423 [Gauge] [CRITICAL] Error: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc0003633b8, 0x1121480, 0x16e2a30)
	C:/hostedtoolcache/windows/go/1.16.13/x64/src/runtime/debug/stack.go:24 +0xa5
main.recoverPanic()
	D:/a/gauge/gauge/gauge.go:27 +0x65
panic(0x1121480, 0x16e2a30)
	C:/hostedtoolcache/windows/go/1.16.13/x64/src/runtime/panic.go:965 +0x1c7
github.com/getgauge/gauge/runner.(*GrpcRunner).ExecuteMessageWithTimeout(0x0, 0xc000160000, 0xc000363600, 0xc000d42200, 0x0)
	D:/a/gauge/gauge/runner/grpcRunner.go:195 +0x29
github.com/getgauge/gauge/validation.(*SpecValidator).validateStep(0xc000d42040, 0xc000303400, 0xc0009ad280, 0x32)
	D:/a/gauge/gauge/validation/validate.go:345 +0x1ba
github.com/getgauge/gauge/validation.(*SpecValidator).Step(0xc000d42040, 0xc000303400)
	D:/a/gauge/gauge/validation/validate.go:313 +0x5c5
github.com/getgauge/gauge/gauge.(*Specification).Traverse(0xc00017d440, 0x12fb7f8, 0xc000d42040, 0xc000363988)
	D:/a/gauge/gauge/gauge/specification.go:261 +0x26a
github.com/getgauge/gauge/validation.(*SpecValidator).validate(0xc000d42040, 0xc000d42040, 0x13, 0x100000001)
	D:/a/gauge/gauge/validation/validate.go:298 +0x94
github.com/getgauge/gauge/validation.(*validator).Validate(0xc000363b38, 0x12fad00)
	D:/a/gauge/gauge/validation/validate.go:284 +0x11c
github.com/getgauge/gauge/validation.ValidateSpecs(0xc00009c140, 0x1, 0x4, 0x0, 0x0)
	D:/a/gauge/gauge/validation/validate.go:174 +0x245
github.com/getgauge/gauge/execution.glob..func1(0xc00009c140, 0x1, 0x4, 0x0)
	D:/a/gauge/gauge/execution/execute.go:107 +0x119
github.com/getgauge/gauge/cmd.execute(0x16f0760, 0xc00009c140, 0x1, 0x4)
	D:/a/gauge/gauge/cmd/run.go:241 +0x22e
github.com/getgauge/gauge/cmd.glob..func12(0x16f0760, 0xc00009c140, 0x1, 0x4)
	D:/a/gauge/gauge/cmd/run.go:90 +0x26e
github.com/spf13/cobra.(*Command).execute(0x16f0760, 0xc00009c100, 0x4, 0x4, 0x16f0760, 0xc00009c100)
	C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x16ee6e0, 0x0, 0xc000073f78, 0xc00012df78)
	C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/getgauge/gauge/cmd.Parse(0xa0b901, 0x0)
	D:/a/gauge/gauge/cmd/cmd.go:112 +0x45
main.main()
	D:/a/gauge/gauge/gauge.go:19 +0x4f

**Comment by marnee01** [comment]
Considering this has been an open issue for so long, I'll be recommending to my company that we switch to a different framework. This is unacceptable.

**Comment by antondebeer** [comment]
Is there a solution for this issue?
