### ISSUE TITLE
Getting UnmodifiableIterator exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#99]
**Expected behavior**
I should be able to run the specifications without an exception.

**Actual behavior**
Getting the following exception
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:60)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
	at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:81)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:53)
[ValidationError] /Users/sswaroop/work/gauge-gradle-sample/specs/main.spec:10 Connection closed [127.0.0.1:55993] cause: EOF => 'A context step which gets executed before every scenario'
[ValidationError] /Users/sswaroop/work/gauge-gradle-sample/specs/main.spec:17 write tcp 127.0.0.1:55989->127.0.0.1:55993: use of closed network connection => 'Say "hello (from main)" to "gauge"'
process /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java with pid 3773 quit unexpectedly. exit status 1
  Failed to initialize suite datastore. Error: write tcp 127.0.0.1:55989->127.0.0.1:55993: use of closed network connection
```
**Step to replicate**
* [Project](https://github.com/manupsunny/gauge-gradle-sample)
* Update the gradle version to 4.0 in the gradle-wrapper.properties
* rename the highest spec folder to specs
* run the project from IDE/commandline

**Version**
```
Gauge version: 0.9.0.nightly-2017-07-06

Plugins
-------
html-report (4.0.1)
java (0.6.5.nightly-2017-07-03)
```

**Comment by MaxBt** [comment]
I had the same issue.
```
>gauge -v
Gauge version: 0.8.5

Plugins
-------
html-report (4.0.1)
java (0.6.4)
spectacle (0.1.2)
```

I have solved it by downgrading to 0.6.2 java plugin version (install plugin and point pom.xml use it). Seems like this issue is present since 0.6.3.

**Comment by jackperalta** [comment]
i cannot reproduce this anymore - so either it is obsolete or I do something wrong....

I checked out the project, changed to gradle-4.0 and ran `gradlew gauge` with success

```
$ gauge -v
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.7)
screenshot (0.0.1)
spectacle (0.1.2)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
